---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: create user tomcat
    user:
      name: tomcat
      state: absent
      shell: /bin/false
      home: "/opt/tomcat"
  - name: download tomcat
    copy:
      src: /home/onworks/Downloads/apache-tomcat-9.0.69.tar.gz 
      dest: /root/apache-tomcat-9.0.69.tar.gz
  - name: Extract tomcat.gz into 
    unarchive:
      src: /root/apache-tomcat-9.0.69.tar.gz
      dest: /opt/tomcat
  - name: change ownership of /opt/tomcat to tomcat
    file:
      path: /opt/tomcat
      state: directory
      recurse: yes
      owner: tomcat
      group: tomcat
  - name: give execute permission to bin/*.sh 
    file:
      path: /opt/tomcat/apache-tomcat-9.0.69/bin/*.sh
      state: directory
      recurse: yes
      mode: ugo+x 
  - name: create file 'tomcat.service'
    copy:
      src: /root/tomcat.service
      dest: /etc/systemd/system/tomcat.service
      mode: '0664'
  - name: create tomcat-users.xml
    template:
      src: /root/tomcat-users.xml.j2
      dest: /opt/tomcat/apache-tomcat-9.0.69/conf/tomcat-users.xml
  - name: reload daemon
    systemd: daemon_reload=yes
  - name: start & enable tomcat service
    service:
      name: tomcat
      state: started
      enabled: yes
  - name: add port & zone in Firewall
    firewalld:
      port: 8080/tcp
      permanent: true
      state: enabled
      zone: public
  - name: reload service firewalld
    systemd:
      name: firewalld
      state: reloaded
  
